export const actions = {
  SET_LOGIN: "SET_LOGIN",
  SET_DATA: "SET_DATA",
  LOGOUT: "LOGOUT",
  LOGIN_ERROR: "ERROR",
  SET_SEARCHED_USER_DATA: "SEARCHED_USER_DATA",
  SET_FOLLOWERS_LIST: "SET_FOLLOWERS_LIST",
};
